//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veneracion_Database {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Veneracion_Database.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select EmployeeID,LastName,FirstName, JobTitle,
        ///FORMAT(DOB,&apos;MM/dd/yyyy&apos;) AS DOB,FORMAT(HireDate,&apos;MM/dd/yyyy&apos;)AS HireDate,
        ///FORMAT(MonthlySalary,&apos;c&apos;) AS MonthlySalary,FORMAT(SalesAmt,&apos;c&apos;) AS SalesAmt,
        ///BonusRate,FORMAT(CarAllowance,&apos;c&apos;) AS CarAllowance,FORMAT(BonusAmount,&apos;c&apos;) AS BonusAmount,
        ///FORMAT((ISNULL(MonthlySalary,0)+((ISNULL(BonusRate,0)/100) * ISNULL(MonthlySalary,0))+ISNULL(CarAllowance,0)),&apos;c&apos;) AS TotalCompensation
        ///FROM dbo.EmployeeInformation
        ///ORDER BY JobTitle, MonthlySalary ASC;.
        /// </summary>
        internal static string GrandTotal {
            get {
                return ResourceManager.GetString("GrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///INSERT INTO Employees (EmployeeID,LastName, FirstName, DOB)
        ///VALUES (101,&apos;Gates&apos;,&apos;William&apos;,&apos;11/03/1984&apos;);
        ///INSERT INTO Employees (EmployeeID,LastName, FirstName, DOB)
        ///VALUES (102,&apos;Garcia&apos;,&apos;Estella&apos;,&apos;10/11/1997&apos;);
        ///INSERT INTO Employees (EmployeeID,LastName, FirstName, DOB)
        ///VALUES (103,&apos;Goode&apos;,&apos;April&apos;,&apos;06/11/1989&apos;);
        ///INSERT INTO Employees (EmployeeID,LastName, FirstName, DOB)
        ///VALUES (203,&apos;Simpson&apos;,&apos;Homer&apos;,&apos;01/05/1987&apos;);
        ///INSERT INTO Employees (EmployeeID,LastName, FirstName, DOB)
        ///VALUES (202,&apos;Chan&apos;,&apos;He [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertValues {
            get {
                return ResourceManager.GetString("InsertValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF (NOT EXISTS (SELECT *
        ///   FROM INFORMATION_SCHEMA.TABLES
        ///   WHERE TABLE_SCHEMA = &apos;dbo&apos;
        ///   AND TABLE_NAME = &apos;EmployeeInformation&apos;))
        ///BEGIN
        ///	SELECT e.EmployeeID, e.LastName,e.FirstName,
        ///	jt.JobTitle,e.DOB,ej.HireDate,
        ///	ej.MonthlySalary, 
        ///	 ISNULL(s.SalesAmt,0) as SalesAmt, ISNULL(b.BonusRate,0)AS BonusRate, ISNULL(c.CarAllowance,0) AS CarAllowance,
        ///	((ISNULL(b.BonusRate,0)/100) * ISNULL(MonthlySalary,0)) AS BonusAmount 
        ///	INTO dbo.EmployeeInformation
        ///	FROM Employees AS e
        ///	LEFT OUTER JOIN EmployeeJ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectEmployees {
            get {
                return ResourceManager.GetString("SelectEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select EmployeeID,LastName,FirstName, JobTitle,
        ///FORMAT(DOB,&apos;MM/dd/yyyy&apos;) AS DOB,FORMAT(HireDate,&apos;MM/dd/yyyy&apos;)AS HireDate,
        ///FORMAT(MonthlySalary,&apos;c&apos;) AS MonthlySalary,FORMAT(SalesAmt,&apos;c&apos;) AS SalesAmt,
        ///BonusRate,FORMAT(CarAllowance,&apos;c&apos;) AS CarAllowance,FORMAT(BonusAmount,&apos;c&apos;) AS BonusAmount,
        ///FORMAT((ISNULL(MonthlySalary,0)+((ISNULL(BonusRate,0)/100) * ISNULL(MonthlySalary,0))+ISNULL(CarAllowance,0)),&apos;c&apos;) AS TotalCompensation
        ///FROM dbo.EmployeeInformation
        ///ORDER BY JobTitle, MonthlySalary ASC;.
        /// </summary>
        internal static string SortJobTitleMonthlySalary {
            get {
                return ResourceManager.GetString("SortJobTitleMonthlySalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select EmployeeID,LastName,FirstName, JobTitle,
        ///FORMAT(DOB,&apos;MM/dd/yyyy&apos;) AS DOB,FORMAT(HireDate,&apos;MM/dd/yyyy&apos;)AS HireDate,
        ///FORMAT(MonthlySalary,&apos;c&apos;) AS MonthlySalary,FORMAT(SalesAmt,&apos;c&apos;) AS SalesAmt,
        ///BonusRate,FORMAT(CarAllowance,&apos;c&apos;) AS CarAllowance,FORMAT(BonusAmount,&apos;c&apos;) AS BonusAmount,
        ///FORMAT((ISNULL(MonthlySalary,0)+((ISNULL(BonusRate,0)/100) * ISNULL(MonthlySalary,0))+ISNULL(CarAllowance,0)),&apos;c&apos;) AS TotalCompensation
        ///FROM dbo.EmployeeInformation
        ///ORDER BY JobTitle, TotalCompensation ASC;.
        /// </summary>
        internal static string SortJobTitleTotalCompensation {
            get {
                return ResourceManager.GetString("SortJobTitleTotalCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF (NOT EXISTS (SELECT * 
        ///                 FROM INFORMATION_SCHEMA.TABLES 
        ///                 WHERE TABLE_SCHEMA = &apos;dbo&apos; 
        ///                 AND  TABLE_NAME = &apos;Employees&apos;))
        ///BEGIN
        ///
        ///	CREATE TABLE Employees (
        ///		EmployeeID INT NOT NULL,
        ///		LastName VARCHAR(50) NOT NULL,
        ///		FirstName VARCHAR(50) NOT NULL,
        ///		DOB DATE NOT NULL,
        ///		CONSTRAINT PK_Employees PRIMARY KEY (EmployeeID)
        ///	);
        ///
        ///END
        ///
        ///IF (NOT EXISTS (SELECT * 
        ///                 FROM INFORMATION_SCHEMA.TABLES 
        ///                 WHERE TABLE_SCHEMA = &apos;db [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VeneracionDatabase {
            get {
                return ResourceManager.GetString("VeneracionDatabase", resourceCulture);
            }
        }
    }
}
